<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="robot">

    
    <xacro:include filename="inertial_macros.xacro"/>

    <xacro:property name="chassis_length" value="0.23" /> 
    <xacro:property name="chassis_width" value="0.14" /> 
    <xacro:property name="chassis_height" value="0.10" /> 
    <xacro:property name="chassis_mass" value="1.0" /> 
    <xacro:property name="wheel_radius" value="0.033" /> 
    <xacro:property name="wheel_thickness" value="0.026" /> 
    <xacro:property name="wheel_mass" value="0.5" /> 
    <xacro:property name="wheel_offset_x" value="0.025" /> 
    <xacro:property name="wheel_offset_y" value="${chassis_width/2 + wheel_thickness/2 - 0.01}" /> 
    <xacro:property name="wheel_offset_z" value="-${chassis_width/2 - 0.036}" /> 
    <xacro:property name="caster_wheel_radius" value="0.012" /> 
    <xacro:property name="caster_wheel_mass" value="0.5" /> 
    <xacro:property name="caster_wheel_offset_x" value="-0.08" /> 
    <xacro:property name="caster_wheel_offset_z" value="-0.058" /> 


    <xacro:property name="meshpath" value="/home/dev/dev_ws/src/wally" /> 

    <material name="yellow">
        <color rgba="1 1 0 1 " />
    </material>

    <material name="black">
        <color rgba="0 0 0 1 " />-
    </material>

    <material name="red">
        <color rgba="1 0 0 1 " />
    </material>

    <material name="grey">
        <color rgba="0.5 0.5 0.5 1 " />
    </material>

    <!-- BASE LINK-->

    <link name="base_link"></link>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint"></link>

    <!-- CHASSIS-->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="-0.01 0 ${chassis_height/2}" />
    </joint>
z
    <link name="chassis">
        <visual>
            <geometry>
                <mesh filename="file://${meshpath}/meshes/stl/Cube.023.stl" scale="1.0 1.0 1.0"/>
                <!--<box size="${chassis_length} ${chassis_width} ${chassis_height}"/>-->
            </geometry>  
            <material name="black"/>  
        </visual>
        <collision>
            <origin xyz="0 0 0" />
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>   
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- LEFT WHEEL LINK-->

    <joint name="left_wheel_joint" type="continuous">
        <origin xyz="${wheel_offset_x} ${wheel_offset_y} ${wheel_offset_z}" rpy="-${pi/2} 0 0"/>
        <parent link="chassis"/>
        <child link="left_wheel"/>  
        <axis xyz="0 0 1"/>
          
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <!--<cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>-->
                <mesh filename="file://${meshpath}/meshes/stl/Cylinder.036.stl" scale="1.0 1.0 1.0"/>   
            </geometry>
            <material name="yellow"/>    
        </visual>
        <collision>
            <geometry>   
                <sphere radius="${wheel_radius}"/>    
            </geometry> 
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Yellow</material>
    </gazebo>

    <!-- RIGHT WHEEL LINK-->blue

    <joint name="right_wheel_joint" type="continuous">
        <origin xyz="${wheel_offset_x} -${wheel_offset_y} ${wheel_offset_z}" rpy="${pi/2} 0 0"/>
        <parent link="chassis"/>
        <child link="right_wheel"/>  
        <axis xyz="0 0 -1"/>
          
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <!--<cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>-->
                <mesh filename="file://${meshpath}/meshes/stl/Cylinder.036.stl" scale="1.0 1.0 1.0"/>       
            </geometry>
            <material name="yellow"/>    
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>  
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Yellow</material>
    </gazebo>

    <!-- CASTER WHEEL-->

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel"/>
        <origin xyz="${caster_wheel_offset_x} 0 ${caster_wheel_offset_z}"/>
    </joint>

    <link name="caster_wheel">
        <visual>
            <geometry>
                <!--<sphere radius="${caster_wheel_radius}"/>-->
                <mesh filename="file://${meshpath}/meshes/stl/Cube.020.stl" scale="1.0 1.0 1.0"/>    
            </geometry> 
            <material name="grey"/>     
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>    
            </geometry>  
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/> 
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel">
        <material>Gazebo/Yellow</material>
        <mu1 value="0.0001"/>
        <mu2 value="0.0001"/>
    </gazebo>

</robot>
